Clarify, update parts of README
pulibrary/dacs_handbook pull request #18
Opened 2022-05-09 02:35 UTC by kevinreiss

2022-05-09 02:40 UTC, christinach requested changes

2022-05-09 02:40 UTC, christinach commented on README.md
> +The Team is responsible for the discovery systems, web sites, business applications and data management for the library. We all work remotely at least two days per week. We have daily check-ins to st
we should remove: 'we have two open positions within the team'

2022-05-09 12:41 UTC, carolyncole requested changes

2022-05-09 12:41 UTC, carolyncole commented on README.md
> +The Team collaborates closely with the three staff members (also currently reporting to team's manager) who manage our Alma platform to support the integrations (indexing, availability, requesting) w
Can we change this to `three staff members in Catalog and Metdata Services (CAMS)`

2022-05-13 11:43 UTC, carolyncole approved these changes

2022-05-13 11:54 UTC, christinach approved these changes

2022-05-13 11:54 UTC, merged