Accounts and Alma
pulibrary/dacs_handbook pull request #20
Opened 2022-05-13 13:05 UTC by kevinreiss

2022-05-13 13:29 UTC, christinach commented on accounts.md
> +* Ciricle CI - Via Github Account
small typo, change to [CircleCi](https://circleci.com/)

2022-05-13 13:29 UTC, christinach commented on accounts.md
> +*
[Honeybadger](https://www.honeybadger.io/)

2022-05-13 13:29 UTC, christinach commented on accounts.md
> +* Datadog - monitoring and alerts
[Datadog](https://www.datadoghq.com/)

2022-05-13 13:29 UTC, christinach commented on accounts.md
> +*
[Amazon AWS](https://princeton.edu/aws)

2022-05-13 13:29 UTC, christinach commented on alma.md
> +* Production Login URL
[Production Login URL](https://princeton.alma.exlibrisgroup.com/SAML)

2022-05-13 13:29 UTC, christinach commented on alma.md
> +* Sandbox Login URL
[Sandbox Login URL](https://princeton-psb.alma.exlibrisgroup.com/SAML)

2022-05-13 13:29 UTC, christinach commented on alma.md
> +* Sandbox Login URL
[Sensu](https://lib-monitor.princeton.edu/dashboard)

2022-05-13 13:53 UTC, carolyncole requested changes

2022-05-13 13:53 UTC, carolyncole commented on accounts.md
> +* Aeon
May want to mention they are only accessible via remote desktop

2022-05-13 13:53 UTC, carolyncole commented on accounts.md
> +  Peoplesoft
Can you push this up a line?  I thought it was something separate, since it was on it's own line

2022-05-17 12:54 UTC, christinach commented on alma.md
> +* Sandbox Login URL
[Pulbot](https://github.com/pulibrary/pulbot) for deployments

2022-06-10 21:37 UTC, sandbergja approved these changes

2022-06-10 21:38 UTC, merged